version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    container_name: nodeApp
    depends_on:
      - mongodb
    build: server
    restart: unless-stopped
    ports:
      - 4000:4000
  client:
    container_name: React
    depends_on:
      - mongodb
      - app
    build: client
    restart: unless-stopped
    ports:
      - 3000:3000
volumes:
  db: